export interface Prospect { id:string; company:string; website:string; industry:string; jobTitle:string; solution:string; prototypeName:string; businessProblem:string; painSignal:string; latestActivity:string; whyNow:string; personalisation:string; trackingCode:string; }
export const prospects: Prospect[] = [
  {
    "id": "NL-0001",
    "company": "JBC Roof Cover",
    "website": "https://jbcroofcover.co.za",
    "industry": "Roofing / home services",
    "jobTitle": "Owner / Ops Manager",
    "solution": "Lead Machine",
    "prototypeName": "JBC Enquiry Recovery Centre",
    "businessProblem": "Roof-leak enquiries can become slow, unstructured WhatsApp conversations.",
    "painSignal": "Public positioning includes roof-repair enquiries and a strong local service footprint; the outreach brief identified photo-first leak qualification and missed-lead recovery.",
    "latestActivity": "Current prospect mapping: rainy-season urgent enquiries; photo-first roof-leak qualification proposed.",
    "whyNow": "Urgent service demand is time-sensitive; faster qualification is directly tied to booking conversion.",
    "personalisation": "Public positioning includes roof-repair enquiries and a strong local service footprint; the outreach brief identified photo-first leak qualification and missed-lead recovery.",
    "trackingCode": "1yphi9z"
  },
  {
    "id": "NL-0002",
    "company": "S60 Rapid Plumbing",
    "website": "https://s60rapid-plumbing.co.za",
    "industry": "Plumbing",
    "jobTitle": "Director / Owner",
    "solution": "Lead Machine",
    "prototypeName": "24/7 Plumbing Triage Centre",
    "businessProblem": "Emergency enquiries arrive outside office hours and need rapid routing.",
    "painSignal": "The outreach brief specifically identifies 24/7 emergency triage and booking as the clearest workflow.",
    "latestActivity": "Current prospect mapping: demand outside office hours.",
    "whyNow": "Emergency leads decay quickly when response is delayed.",
    "personalisation": "The outreach brief specifically identifies 24/7 emergency triage and booking as the clearest workflow.",
    "trackingCode": "1km79gw"
  },
  {
    "id": "NL-0003",
    "company": "Supa Nova Electrical, Plumbing and Solar",
    "website": "https://supanova.co.za",
    "industry": "Electrical / plumbing / solar",
    "jobTitle": "Owner / Ops Manager",
    "solution": "Lead Machine",
    "prototypeName": "Dual-Trade Lead Qualification",
    "businessProblem": "Different service lines require different qualification paths.",
    "painSignal": "The outreach brief identifies dual-trade qualification plus solar lead scoring.",
    "latestActivity": "Current prospect mapping: multi-service qualifier and solar lead scoring.",
    "whyNow": "A single structured intake can stop mixed enquiries from reaching the wrong team.",
    "personalisation": "The outreach brief identifies dual-trade qualification plus solar lead scoring.",
    "trackingCode": "1iyz21m"
  },
  {
    "id": "NL-0004",
    "company": "Roof Guys",
    "website": "https://roofguys.co.za",
    "industry": "Roofing",
    "jobTitle": "",
    "solution": "Lead Machine",
    "prototypeName": "Roof Quote Qualifier",
    "businessProblem": "Quote requests need roof photos, location and scope before a useful estimate.",
    "painSignal": "The outreach brief calls out photo + location + estimate qualification; contact research currently only identifies Sean by first name.",
    "latestActivity": "Current prospect mapping: Sandton roofing enquiry qualification.",
    "whyNow": "High-value home-service leads benefit from fewer back-and-forth messages.",
    "personalisation": "The outreach brief calls out photo + location + estimate qualification; contact research currently only identifies Sean by first name.",
    "trackingCode": "1tdjv26"
  },
  {
    "id": "NL-0005",
    "company": "Randburg Auto Repairs",
    "website": "https://randburgautorepairs.co.za",
    "industry": "Automotive services",
    "jobTitle": "Owner",
    "solution": "Lead Machine",
    "prototypeName": "After-Hours Auto Enquiry Desk",
    "businessProblem": "Breakdown and diagnostic enquiries arrive after hours.",
    "painSignal": "The outreach brief identifies WhatsApp being office-hours only and recommends after-hours triage + diagnostic booking.",
    "latestActivity": "Current prospect mapping: after-hours breakdown triage.",
    "whyNow": "Breakdown demand is immediate and can move to competitors when response is slow.",
    "personalisation": "The outreach brief identifies WhatsApp being office-hours only and recommends after-hours triage + diagnostic booking.",
    "trackingCode": "0va13qs"
  },
  {
    "id": "NL-0006",
    "company": "Bliss Renovations",
    "website": "https://blissrenovations.co.za",
    "industry": "Renovations",
    "jobTitle": "Owner",
    "solution": "Lead Machine",
    "prototypeName": "Renovation Scope & Site Visit Desk",
    "businessProblem": "Renovation enquiries need scope, budget and site-visit qualification.",
    "painSignal": "Public contact research found a Gmail address but did not establish that it belongs to the owner.",
    "latestActivity": "Personal email not safely attributable; use the business inbox only after confirmation.",
    "whyNow": "A structured scope intake can reduce admin before site visits.",
    "personalisation": "Public contact research found a Gmail address but did not establish that it belongs to the owner.",
    "trackingCode": "1lxcn2d"
  },
  {
    "id": "NL-0007",
    "company": "Prime Secure",
    "website": "",
    "industry": "Security / locksmith",
    "jobTitle": "Owner / Operations",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need immediate triage and dispatch.",
    "painSignal": "The solution mapping groups Prime Secure with HTC and Goldman Locksmiths for 24/7 emergency triage.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "whyNow": "Emergency-response workflows are a strong fit for structured WhatsApp intake.",
    "personalisation": "The solution mapping groups Prime Secure with HTC and Goldman Locksmiths for 24/7 emergency triage.",
    "trackingCode": "1y27tou"
  },
  {
    "id": "NL-0008",
    "company": "HTC Locksmiths",
    "website": "",
    "industry": "Locksmith",
    "jobTitle": "Owner / Operations",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need location, urgency and access details.",
    "painSignal": "The solution mapping groups HTC with Prime Secure and Goldman Locksmiths for 24/7 emergency triage.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "whyNow": "Fast routing is the business outcome; not another chatbot.",
    "personalisation": "The solution mapping groups HTC with Prime Secure and Goldman Locksmiths for 24/7 emergency triage.",
    "trackingCode": "0uwv6qp"
  },
  {
    "id": "NL-0009",
    "company": "Goldman Locksmiths",
    "website": "",
    "industry": "Locksmith",
    "jobTitle": "Owner / Operations",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need location, urgency and access details.",
    "painSignal": "The solution mapping identifies a 24/7 emergency triage + dispatch intake.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "whyNow": "Immediate routing protects response time and booking conversion.",
    "personalisation": "The solution mapping identifies a 24/7 emergency triage + dispatch intake.",
    "trackingCode": "1ir98vh"
  },
  {
    "id": "NL-0010",
    "company": "JMT Handyman",
    "website": "https://jmthandymanservices.co.za",
    "industry": "Handyman",
    "jobTitle": "Owner",
    "solution": "Lead Machine",
    "prototypeName": "JMT Quote Recovery Desk",
    "businessProblem": "Service and area qualification plus after-hours quote recovery are currently manual.",
    "painSignal": "The outreach brief says the business sells WhatsApp quotes and 30–60 minute response; personal email was not publicly found.",
    "latestActivity": "Current prospect mapping: service/area/urgency qualifier and after-hours recovery.",
    "whyNow": "A deterministic intake can protect the 30–60 minute response promise.",
    "personalisation": "The outreach brief says the business sells WhatsApp quotes and 30–60 minute response; personal email was not publicly found.",
    "trackingCode": "1la3d2j"
  },
  {
    "id": "NL-0011",
    "company": "Etchells and Young Property Brokers",
    "website": "https://www.etchellsandyoung.co.za",
    "industry": "Property / real estate",
    "jobTitle": "Property Broker",
    "solution": "Lead Machine",
    "prototypeName": "Rental Pre-Qualification Desk",
    "businessProblem": "Rental leads need qualification and viewing scheduling before agent time is consumed.",
    "painSignal": "Direct personal email verified on the company site.",
    "latestActivity": "Latest research confirms public profile and direct work email.",
    "whyNow": "Property leads can be qualified before viewing slots are committed.",
    "personalisation": "Direct personal email verified on the company site.",
    "trackingCode": "13cwal6"
  },
  {
    "id": "NL-0012",
    "company": "Etchells and Young Property Brokers",
    "website": "https://www.etchellsandyoung.co.za",
    "industry": "Property / real estate",
    "jobTitle": "Property Broker",
    "solution": "Lead Machine",
    "prototypeName": "Rental Pre-Qualification Desk",
    "businessProblem": "Rental leads need qualification and viewing scheduling before agent time is consumed.",
    "painSignal": "Direct personal email verified on the company site.",
    "latestActivity": "Latest research confirms public profile and direct work email.",
    "whyNow": "Property leads can be qualified before viewing slots are committed.",
    "personalisation": "Direct personal email verified on the company site.",
    "trackingCode": "03w7fb3"
  },
  {
    "id": "NL-0013",
    "company": "Blakes Maphanga Attorneys",
    "website": "https://blakes.co.za",
    "industry": "Legal",
    "jobTitle": "Managing Partner / Director",
    "solution": "Lead Machine",
    "prototypeName": "Legal Intake & Routing",
    "businessProblem": "Legal enquiries require structured intake and routing rather than long free-text email chains.",
    "painSignal": "Public contact page lists several directors' own emails but does not identify the Managing Partner.",
    "latestActivity": "Latest research found Feyoena Hammann, Lindie Burger, Eugene Meyer and Phethelo Fakude as public directors; exact target contact is not confirmed.",
    "whyNow": "The right prototype is a structured intake and routing layer; do not guess the decision-maker email.",
    "personalisation": "Public contact page lists several directors' own emails but does not identify the Managing Partner.",
    "trackingCode": "1ot6v31"
  },
  {
    "id": "NL-0014",
    "company": "Melrose Dental Studio",
    "website": "https://melrosedental.co.za",
    "industry": "Dental",
    "jobTitle": "Dentist / Owner",
    "solution": "Lead Machine",
    "prototypeName": "Dental Treatment Intent Desk",
    "businessProblem": "Treatment intent needs triage and fast WhatsApp booking.",
    "painSignal": "The outreach mapping identifies treatment-intent triage + WhatsApp booking.",
    "latestActivity": "Current prospect mapping: treatment-intent triage and booking.",
    "whyNow": "High-intent dental enquiries can be lost between first message and booking.",
    "personalisation": "The outreach mapping identifies treatment-intent triage + WhatsApp booking.",
    "trackingCode": "03h578v"
  },
  {
    "id": "NL-0015",
    "company": "Mission Mobile",
    "website": "https://missionmobile.co.za",
    "industry": "Mobile / retail",
    "jobTitle": "Commercial / Owner",
    "solution": "Lead Machine",
    "prototypeName": "Retail Enquiry Qualification",
    "businessProblem": "Product and service enquiries need structured qualification before follow-up.",
    "painSignal": "The solution mapping identifies a retail enquiry Lead Machine.",
    "latestActivity": "Current prospect mapping: retail enquiry qualification.",
    "whyNow": "A lightweight intake can route high-intent retail enquiries to the right person.",
    "personalisation": "The solution mapping identifies a retail enquiry Lead Machine.",
    "trackingCode": "1pd62bj"
  },
  {
    "id": "NL-0016",
    "company": "Inospace",
    "website": "https://inospace.com",
    "industry": "Flexible workspace / property",
    "jobTitle": "Founder / Executive",
    "solution": "Lead Machine",
    "prototypeName": "SME Fulfilment Acquisition Desk",
    "businessProblem": "SME acquisition enquiries need structured qualification and routing.",
    "painSignal": "The solution mapping identifies SME fulfilment acquisition as the Lead Machine use case.",
    "latestActivity": "Current prospect mapping: Lead Machine for SME fulfilment acquisition.",
    "whyNow": "A fast qualification layer can reduce sales admin across multiple enquiry sources.",
    "personalisation": "The solution mapping identifies SME fulfilment acquisition as the Lead Machine use case.",
    "trackingCode": "0n72wvo"
  },
  {
    "id": "NL-0017",
    "company": "Cassims and Co",
    "website": "https://www.cassimsandco.co.za",
    "industry": "Jewellery",
    "jobTitle": "Owner / Management",
    "solution": "Lead Machine",
    "prototypeName": "Jewellery Enquiry Continuity Desk",
    "businessProblem": "Enquiry continuity can break when client relationships sit with one designer.",
    "painSignal": "The outreach mapping explicitly notes lost continuity when a designer left.",
    "latestActivity": "Current prospect mapping: Tier A jewellery intake pack.",
    "whyNow": "The prototype can preserve client context and enquiry continuity without replacing the team.",
    "personalisation": "The outreach mapping explicitly notes lost continuity when a designer left.",
    "trackingCode": "0jqfyrb"
  },
  {
    "id": "NL-0018",
    "company": "Alloy Jewellery Gallery",
    "website": "https://alloygallery.co.za",
    "industry": "Jewellery",
    "jobTitle": "Owner",
    "solution": "Lead Machine",
    "prototypeName": "Jewellery AI-Assist Desk",
    "businessProblem": "A one-person owner can become the bottleneck for enquiries and follow-up.",
    "painSignal": "Direct owner email verified from public company/industry sources.",
    "latestActivity": "Latest research confirms Edna as owner with public direct email.",
    "whyNow": "Reducing owner-only enquiry handling is the clearest operational wedge.",
    "personalisation": "Direct owner email verified from public company/industry sources.",
    "trackingCode": "0dnm8al"
  },
  {
    "id": "NL-0019",
    "company": "Skin Reform",
    "website": "https://skinreform.co.za",
    "industry": "Aesthetic / medical",
    "jobTitle": "Clinic / Medical Team",
    "solution": "Lead Machine",
    "prototypeName": "Aesthetic Treatment Intake",
    "businessProblem": "Branch conversion visibility and safe qualification need structured intake.",
    "painSignal": "The mapping specifies an HPCSA-guardrailed aesthetic/medical intake pack, Tier A.",
    "latestActivity": "Current prospect mapping: branch conversion visibility.",
    "whyNow": "Structured triage can reduce repetitive logistics questions while keeping clinical boundaries clear.",
    "personalisation": "The mapping specifies an HPCSA-guardrailed aesthetic/medical intake pack, Tier A.",
    "trackingCode": "0x0igz2"
  },
  {
    "id": "NL-0020",
    "company": "Arca",
    "website": "https://arca.health",
    "industry": "Aesthetic / medical",
    "jobTitle": "Doctor / Owner",
    "solution": "Lead Machine",
    "prototypeName": "Medical Enquiry AI-Assist",
    "businessProblem": "A doctor is answering logistics questions that could be structured before clinical interaction.",
    "painSignal": "The mapping explicitly notes the doctor answering logistics questions.",
    "latestActivity": "Current prospect mapping: AI-Assist intake.",
    "whyNow": "Route logistics away from clinical time while keeping medical decisions human-led.",
    "personalisation": "The mapping explicitly notes the doctor answering logistics questions.",
    "trackingCode": "1twszz3"
  },
  {
    "id": "NL-0021",
    "company": "Interiology",
    "website": "https://interiology.co.za",
    "industry": "Luxury kitchens",
    "jobTitle": "Owner / Sales",
    "solution": "Lead Machine",
    "prototypeName": "Luxury Kitchen Qualification",
    "businessProblem": "Showroom visits should be preceded by budget and project qualification.",
    "painSignal": "The mapping recommends qualifying budget before showroom visits.",
    "latestActivity": "Current prospect mapping: Tier A luxury-kitchens intake.",
    "whyNow": "A few structured questions can protect expensive showroom time.",
    "personalisation": "The mapping recommends qualifying budget before showroom visits.",
    "trackingCode": "1gt2j74"
  },
  {
    "id": "NL-0022",
    "company": "Sandton Kitchens",
    "website": "https://sandtonkitchens.co.za",
    "industry": "Luxury kitchens",
    "jobTitle": "Owner / Sales",
    "solution": "Lead Machine",
    "prototypeName": "Luxury Kitchen Qualification",
    "businessProblem": "Premium clients expect fast WhatsApp replies and clear project qualification.",
    "painSignal": "The mapping explicitly calls out fast WhatsApp replies.",
    "latestActivity": "Current prospect mapping: Tier A luxury-kitchens intake.",
    "whyNow": "Speed + prequalification is a clear revenue-protection workflow.",
    "personalisation": "The mapping explicitly calls out fast WhatsApp replies.",
    "trackingCode": "01fmo8i"
  },
  {
    "id": "NL-0023",
    "company": "Prestige Marques",
    "website": "",
    "industry": "Automotive",
    "jobTitle": "Owner / Sales",
    "solution": "Lead Machine",
    "prototypeName": "Automotive Voice Qualification",
    "businessProblem": "High-value vehicle enquiries need triage and voice escalation.",
    "painSignal": "The mapping recommends automotive intake with voice escalation because the current personal line lacks triage.",
    "latestActivity": "Current prospect mapping: Tier A automotive intake.",
    "whyNow": "The prototype can separate high-intent buyers from routine questions before escalation.",
    "personalisation": "The mapping recommends automotive intake with voice escalation because the current personal line lacks triage.",
    "trackingCode": "07ph1qq"
  },
  {
    "id": "NL-0024",
    "company": "MG Auto",
    "website": "https://mgauto.co.za",
    "industry": "Automotive",
    "jobTitle": "Owner / Sales",
    "solution": "Lead Machine",
    "prototypeName": "Vehicle Fit Qualification",
    "businessProblem": "Model, inventory and budget fit need to be captured before follow-up.",
    "painSignal": "The mapping specifies model + inventory + budget fit check.",
    "latestActivity": "Current prospect mapping: Tier A automotive intake.",
    "whyNow": "A structured buyer fit check makes sales follow-up more focused.",
    "personalisation": "The mapping specifies model + inventory + budget fit check.",
    "trackingCode": "1ss5lyd"
  },
  {
    "id": "NL-0025",
    "company": "The Baron Group",
    "website": "https://www.thebaron.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Group Management",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Revenue & Retention Centre",
    "businessProblem": "Multi-site ordering and customer intelligence are fragmented across venues.",
    "painSignal": "Existing NahaLabs mapping identifies a multi-site ordering + central customer intelligence use case; current website shows multiple branches and ongoing events/promotions.",
    "latestActivity": "Current public website shows multiple branches with active events/promotions; NahaLabs already has a live pilot mapping with the group.",
    "whyNow": "Multi-site consistency makes centralised WhatsApp/customer intelligence more valuable.",
    "personalisation": "Existing NahaLabs mapping identifies a multi-site ordering + central customer intelligence use case; current website shows multiple branches and ongoing events/promotions.",
    "trackingCode": "1umhmvt"
  },
  {
    "id": "NL-0026",
    "company": "Hogshead Craft Beer",
    "website": "https://hogshead.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Group / Venue Management",
    "solution": "Flavourly",
    "prototypeName": "Hogshead WhatsApp Retention Desk",
    "businessProblem": "Repeat-customer ordering and retention can be improved through structured WhatsApp.",
    "painSignal": "The mapping identifies ordering + repeat-customer intelligence; the current site publishes menus and loyalty-oriented offers.",
    "latestActivity": "Public site currently publishes detailed menu/loyalty content.",
    "whyNow": "A retention layer can turn existing menu and loyalty intent into measurable repeat ordering.",
    "personalisation": "The mapping identifies ordering + repeat-customer intelligence; the current site publishes menus and loyalty-oriented offers.",
    "trackingCode": "0pghzjj"
  },
  {
    "id": "NL-0027",
    "company": "Cafe Caprice",
    "website": "https://www.cafecaprice.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Venue Management",
    "solution": "Flavourly",
    "prototypeName": "Reservations & Tourist Re-Engagement Desk",
    "businessProblem": "Reservation and tourist re-engagement can be lost across busy service periods.",
    "painSignal": "Current public site lists reservations and an active event calendar.",
    "latestActivity": "Recent September 2026 event programming and reservations indicate active venue/event operations.",
    "whyNow": "High event activity creates a strong case for automated reservation handling and post-visit re-engagement.",
    "personalisation": "Current public site lists reservations and an active event calendar.",
    "trackingCode": "16u7bv6"
  },
  {
    "id": "NL-0028",
    "company": "Jack Salmon",
    "website": "https://jacksalmon.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Management",
    "solution": "Flavourly",
    "prototypeName": "Jack Salmon Retention & Promo Intelligence",
    "businessProblem": "Menu and promotional intelligence can improve repeat engagement.",
    "painSignal": "Existing outreach record flags the published role inbox as hard-bounced.",
    "latestActivity": "The known info@jacksalmon.co.za address hard-bounced; do not reuse.",
    "whyNow": "Use only after a verified alternative contact is found.",
    "personalisation": "Existing outreach record flags the published role inbox as hard-bounced.",
    "trackingCode": "0rrzosy"
  },
  {
    "id": "NL-0029",
    "company": "Bravo Pizzeria Hatfield",
    "website": "",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Owner",
    "solution": "Flavourly",
    "prototypeName": "Pizzeria Order Recovery Desk",
    "businessProblem": "Ordering, reorder and abandoned-order recovery can be handled through WhatsApp.",
    "painSignal": "The mapping identifies ordering + reorder + abandoned-order recovery.",
    "latestActivity": "Public business Gmail is available but is not a verified office/personal work address.",
    "whyNow": "Do not treat the Gmail address as personal work email.",
    "personalisation": "The mapping identifies ordering + reorder + abandoned-order recovery.",
    "trackingCode": "0mbcpg4"
  },
  {
    "id": "NL-0030",
    "company": "Woolworths Food Services",
    "website": "https://www.woolworths.co.za",
    "industry": "Food services",
    "jobTitle": "Corporate / Business Services",
    "solution": "Flavourly",
    "prototypeName": "New-Site WhatsApp Ordering Pilot",
    "businessProblem": "New-site food operations create a repeatable WhatsApp revenue workflow opportunity.",
    "painSignal": "The mapping identifies a pilot for new sites.",
    "latestActivity": "Current prospect mapping: new-site pilot.",
    "whyNow": "A repeatable pilot can demonstrate the system before broader rollout.",
    "personalisation": "The mapping identifies a pilot for new sites.",
    "trackingCode": "0zvfy8v"
  },
  {
    "id": "NL-0031",
    "company": "SPAR Southern Africa",
    "website": "https://www.spar.co.za",
    "industry": "Retail / food",
    "jobTitle": "",
    "solution": "Flavourly",
    "prototypeName": "Demand & Delivery Intelligence Pilot",
    "businessProblem": "Demand and delivery signals are fragmented across a large network.",
    "painSignal": "The mapping identifies a demand/delivery intelligence pilot.",
    "latestActivity": "Current prospect mapping: demand/delivery intelligence pilot.",
    "whyNow": "A focused pilot can show value without replacing existing systems.",
    "personalisation": "The mapping identifies a demand/delivery intelligence pilot.",
    "trackingCode": "039tbv0"
  },
  {
    "id": "NL-0032",
    "company": "Hungry Lion",
    "website": "https://www.hungrylion.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Management",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Operations Intelligence",
    "businessProblem": "Restaurant operations create repeatable ordering, customer and retention workflows.",
    "painSignal": "The mapping identifies a restaurant ops layer with Flavourly later.",
    "latestActivity": "Current prospect mapping: restaurant operations layer.",
    "whyNow": "Use the prototype to show one operational loop before asking for a broad deployment.",
    "personalisation": "The mapping identifies a restaurant ops layer with Flavourly later.",
    "trackingCode": "03pjthc"
  },
  {
    "id": "NL-0033",
    "company": "Pedros Chicken",
    "website": "https://pedroschicken.co.za",
    "industry": "Restaurants / hospitality",
    "jobTitle": "Executive / Owner",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Ops & Customer Intelligence",
    "businessProblem": "Multi-channel customer demand creates an opportunity for WhatsApp ordering/ops intelligence.",
    "painSignal": "Peter Erasmus direct work email was found via his own LinkedIn post.",
    "latestActivity": "Public LinkedIn activity from Peter Erasmus provides a direct email and phone contact.",
    "whyNow": "A direct route to the operator makes the prototype-first approach practical.",
    "personalisation": "Peter Erasmus direct work email was found via his own LinkedIn post.",
    "trackingCode": "1byp896"
  },
  {
    "id": "NL-0034",
    "company": "Life and Brand Portfolio",
    "website": "https://lifeandbrand.co.za",
    "industry": "Hospitality",
    "jobTitle": "Executive",
    "solution": "Flavourly",
    "prototypeName": "Venue Booking & Reminder Desk",
    "businessProblem": "A portfolio with many venues and seasonal hiring creates repeatable booking workflows.",
    "painSignal": "The mapping identifies 33 restaurants and seasonal hiring.",
    "latestActivity": "Current prospect mapping: start with one venue and extend after proof.",
    "whyNow": "Pilot in one venue before expanding across the portfolio.",
    "personalisation": "The mapping identifies 33 restaurants and seasonal hiring.",
    "trackingCode": "0j5wp40"
  },
  {
    "id": "NL-0035",
    "company": "Twelve Apostles Hotel",
    "website": "https://12apostleshotel.com",
    "industry": "Hospitality",
    "jobTitle": "Operations / Reservations",
    "solution": "AI Employee",
    "prototypeName": "Hospitality Reservation Employee",
    "businessProblem": "Reservation enquiries, preferences, waitlist and escalation create repetitive front-desk work.",
    "painSignal": "The mapping identifies an AI reservation employee use case.",
    "latestActivity": "Current prospect mapping: reservations, preferences, waitlist and escalation.",
    "whyNow": "This is a contained AI employee workflow with clear human escalation boundaries.",
    "personalisation": "The mapping identifies an AI reservation employee use case.",
    "trackingCode": "1j0g6w0"
  },
  {
    "id": "NL-0036",
    "company": "ZDS Recruit",
    "website": "",
    "industry": "Recruitment / hospitality",
    "jobTitle": "Founder / Recruiter",
    "solution": "Flavourly",
    "prototypeName": "Recruitment Channel Intelligence",
    "businessProblem": "Recruitment-related bookings/reminders/triage are repetitive and time-sensitive.",
    "painSignal": "The mapping identifies hospitality reservations hiring and recruitment channel intelligence.",
    "latestActivity": "Current prospect mapping: booking/reminders/triage and recruitment channel intelligence.",
    "whyNow": "A prototype can show the workflow end to end before integrating a production ATS.",
    "personalisation": "The mapping identifies hospitality reservations hiring and recruitment channel intelligence.",
    "trackingCode": "1c8teoe"
  },
  {
    "id": "NL-0037",
    "company": "Positive Freight Solutions",
    "website": "",
    "industry": "Freight / logistics",
    "jobTitle": "Container Division",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "DGT Demurrage Evidence Room",
    "businessProblem": "DGT slot failures create demurrage, waiting time and dispute evidence gaps.",
    "painSignal": "The outreach mapping explicitly cites Alex Hill discussing the DGT slot problem.",
    "latestActivity": "Public industry evidence and the prospect mapping both point to DGT slot/disruption recovery.",
    "whyNow": "The prototype can turn a disputed delay into a defensible evidence timeline.",
    "personalisation": "The outreach mapping explicitly cites Alex Hill discussing the DGT slot problem.",
    "trackingCode": "12k2wbf"
  },
  {
    "id": "NL-0038",
    "company": "Internet Express / Citisprint",
    "website": "",
    "industry": "Logistics / last mile",
    "jobTitle": "Managing Director",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Driver POD Evidence Room",
    "businessProblem": "Rapid growth with owner-drivers can create proof-of-delivery and driver onboarding gaps.",
    "painSignal": "Diederick posted about successfully launching a major international e-commerce account and completing first deliveries.",
    "latestActivity": "Internet Express launched a major international e-commerce account and completed first deliveries; Diederick also promoted an eCommerceLive 2026 session on delivery convenience.",
    "whyNow": "Growth increases the need for structured POD and exception evidence.",
    "personalisation": "Diederick posted about successfully launching a major international e-commerce account and completing first deliveries.",
    "trackingCode": "1tr0v7z"
  },
  {
    "id": "NL-0039",
    "company": "Savino Del Bene",
    "website": "https://www.savinodelbene.com",
    "industry": "Freight forwarding",
    "jobTitle": "Operations / Client",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "DGT Cancellation Evidence Pack",
    "businessProblem": "Cancelled truck appointments need timestamped evidence and client alerts.",
    "painSignal": "The mapping identifies cancelled DGT truck appointments and dispute timelines.",
    "latestActivity": "Current prospect mapping: cancellation timestamps, client alerts, dispute timelines.",
    "whyNow": "Build evidence at the point of exception instead of after a dispute starts.",
    "personalisation": "The mapping identifies cancelled DGT truck appointments and dispute timelines.",
    "trackingCode": "19el2dp"
  },
  {
    "id": "NL-0040",
    "company": "Intelligent Security Systems",
    "website": "",
    "industry": "Security / logistics",
    "jobTitle": "Management",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Incident Evidence Pack",
    "businessProblem": "Timestamped handover evidence and incident packs can strengthen dispute and fraud workflows.",
    "painSignal": "The mapping cites a cargo-fraud article and timestamped evidence use case.",
    "latestActivity": "Current prospect mapping: handover evidence + incident packs.",
    "whyNow": "Evidence quality improves when the timeline is assembled continuously.",
    "personalisation": "The mapping cites a cargo-fraud article and timestamped evidence use case.",
    "trackingCode": "0xa0puf"
  },
  {
    "id": "NL-0041",
    "company": "SATI",
    "website": "https://sati.co.za",
    "industry": "Agriculture / exports",
    "jobTitle": "Industry Association",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Cold-Chain Evidence Room",
    "businessProblem": "Exporters need defensible cold-chain and port evidence when cargo is delayed.",
    "painSignal": "The mapping identifies cold-chain and port evidence use cases.",
    "latestActivity": "Current prospect mapping: cold-chain and port evidence.",
    "whyNow": "A standard evidence layer can serve many exporters without replacing their operational systems.",
    "personalisation": "The mapping identifies cold-chain and port evidence use cases.",
    "trackingCode": "0mw5vou"
  },
  {
    "id": "NL-0042",
    "company": "Hortgro",
    "website": "https://www.hortgro.co.za",
    "industry": "Agriculture / exports",
    "jobTitle": "Industry Association",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Cold-Chain Evidence Room",
    "businessProblem": "Exporters need defensible cold-chain and port evidence when cargo is delayed.",
    "painSignal": "The mapping identifies cold-chain and port evidence use cases.",
    "latestActivity": "Current prospect mapping: cold-chain and port evidence.",
    "whyNow": "Standard evidence can reduce disputes across members.",
    "personalisation": "The mapping identifies cold-chain and port evidence use cases.",
    "trackingCode": "1n1jv3b"
  },
  {
    "id": "NL-0043",
    "company": "FPEF",
    "website": "https://fpef.co.za",
    "industry": "Agriculture / exports",
    "jobTitle": "Industry Association",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Exporter Evidence Standard",
    "businessProblem": "Exporters need structured evidence across port and cold-chain events.",
    "painSignal": "The mapping identifies cold-chain and port evidence for FPEF and peers.",
    "latestActivity": "Current prospect mapping: export evidence standard.",
    "whyNow": "A shared evidence template can make recurring disputes easier to resolve.",
    "personalisation": "The mapping identifies cold-chain and port evidence for FPEF and peers.",
    "trackingCode": "0u15807"
  },
  {
    "id": "NL-0044",
    "company": "DHL Supply Chain South Africa",
    "website": "https://www.dhl.com/za-en/home/our-divisions/supply-chain.html",
    "industry": "Logistics",
    "jobTitle": "Operations / Supply Chain",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Operational Evidence Pilot",
    "businessProblem": "Large operational networks create high-volume exception and handover evidence.",
    "painSignal": "The mapping identifies an operational evidence pilot.",
    "latestActivity": "Current prospect mapping: operational evidence pilot.",
    "whyNow": "A small evidence pilot can be tested on one exception workflow.",
    "personalisation": "The mapping identifies an operational evidence pilot.",
    "trackingCode": "1mpal4s"
  },
  {
    "id": "NL-0045",
    "company": "ATNS",
    "website": "https://www.atns.co.za",
    "industry": "Aviation / public infrastructure",
    "jobTitle": "Procurement / Fleet",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Fleet Contract Assurance Room",
    "businessProblem": "Fleet procurements require clear contract and operational evidence.",
    "painSignal": "ATNS published an RFP for a 60-month fleet management and vehicle lease service; Andy Ngubane is the enquiry contact.",
    "latestActivity": "ATNS published and updated a 60-month fleet management RFP; tender records name Andy Ngubane as the enquiry contact.",
    "whyNow": "Active fleet procurement is a strong trigger for an evidence/assurance prototype.",
    "personalisation": "ATNS published an RFP for a 60-month fleet management and vehicle lease service; Andy Ngubane is the enquiry contact.",
    "trackingCode": "151pi7z"
  },
  {
    "id": "NL-0046",
    "company": "Midvaal Municipality",
    "website": "https://www.midvaal.gov.za",
    "industry": "Municipal government",
    "jobTitle": "Fleet / Operations",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Fleet Evidence Room",
    "businessProblem": "Municipal fleets need traceable operational evidence for incidents and claims.",
    "painSignal": "The mapping identifies a fleet evidence use case.",
    "latestActivity": "Current prospect mapping: fleet evidence.",
    "whyNow": "A small evidence room can support fleet incidents without replacing fleet systems.",
    "personalisation": "The mapping identifies a fleet evidence use case.",
    "trackingCode": "1xjfnj2"
  },
  {
    "id": "NL-0047",
    "company": "Hollard",
    "website": "https://www.hollard.co.za",
    "industry": "Insurance",
    "jobTitle": "Claims / Operations",
    "solution": "AI Employee",
    "prototypeName": "Claims Evidence & Follow-up Assistant",
    "businessProblem": "Claims intake and evidence chasing are repetitive and auditable workflows.",
    "painSignal": "The mapping identifies claims evidence as a CargoIQ/ImpactTrace opportunity and an AI employee-style workflow.",
    "latestActivity": "Current prospect mapping: claims evidence / decision layer.",
    "whyNow": "Claims evidence is a strong domain where provenance and automation can coexist.",
    "personalisation": "The mapping identifies claims evidence as a CargoIQ/ImpactTrace opportunity and an AI employee-style workflow.",
    "trackingCode": "0606lhg"
  },
  {
    "id": "NL-0048",
    "company": "Netstar",
    "website": "https://www.netstar.co.za",
    "industry": "Telematics / fleet",
    "jobTitle": "Group Managing Director",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Telematics Evidence & Decision Room",
    "businessProblem": "Existing telematics data is valuable but can be difficult to translate into defensible evidence and decisions.",
    "painSignal": "Warren Mande was appointed Managing Director effective 1 July 2026.",
    "latestActivity": "Altron announced Warren Mande as Netstar Managing Director effective 1 July 2026; the company described a new growth chapter.",
    "whyNow": "A decision/evidence layer can sit above existing telematics rather than replace it.",
    "personalisation": "Warren Mande was appointed Managing Director effective 1 July 2026.",
    "trackingCode": "13lerza"
  },
  {
    "id": "NL-0049",
    "company": "Unithink",
    "website": "",
    "industry": "Software / partnerships",
    "jobTitle": "Co-founder",
    "solution": "AI Employee",
    "prototypeName": "WhatsApp Evidence & Workflow Layer",
    "businessProblem": "WhatsApp workflows need structured evidence and action receipts.",
    "painSignal": "Public research found a low-confidence Gmail on a talent directory, not a verified work inbox.",
    "latestActivity": "Current mapping identifies partnership + evidence/decision layer for WhatsApp workflows.",
    "whyNow": "Do not guess or substitute a personal Gmail as a verified work address.",
    "personalisation": "Public research found a low-confidence Gmail on a talent directory, not a verified work inbox.",
    "trackingCode": "0xr1pdw"
  },
  {
    "id": "NL-0050",
    "company": "Citrus Growers' Association",
    "website": "https://www.cga.co.za",
    "industry": "Agriculture / exports",
    "jobTitle": "Industry Association",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Reefer Delay Evidence Room",
    "businessProblem": "Reefer-delay evidence needs to combine operational events and port timelines.",
    "painSignal": "The mapping proposes a reefer-delay evidence pack for exporters due to DGT disruption.",
    "latestActivity": "Current prospect mapping: DGT disruption / reefer-delay evidence.",
    "whyNow": "The prototype can turn scattered events into a single export evidence timeline.",
    "personalisation": "The mapping proposes a reefer-delay evidence pack for exporters due to DGT disruption.",
    "trackingCode": "1nzvukq"
  },
  {
    "id": "NL-0051",
    "company": "SAAFF",
    "website": "https://saaff.org.za",
    "industry": "Freight / trade association",
    "jobTitle": "CEO",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "D&D Evidence Standard",
    "businessProblem": "Industry members need a consistent demurrage & detention evidence standard.",
    "painSignal": "SAAFF lists Dr Juanita Maree as CEO and current 2026 industry leadership activity around ports/rail.",
    "latestActivity": "SAAFF announced Dr Juanita Maree would chair Gateway to Growth at Ports & Rail Week 2026; she also appeared in a Unitrans podcast on cross-border trade.",
    "whyNow": "A common evidence standard fits the association-level problem better than a bespoke tool.",
    "personalisation": "SAAFF lists Dr Juanita Maree as CEO and current 2026 industry leadership activity around ports/rail.",
    "trackingCode": "0mc1hrz"
  },
  {
    "id": "NL-0052",
    "company": "Kumba Iron Ore",
    "website": "https://www.angloamericankumba.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Marketing & Sales / commercial contact",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Iron Ore Corridor Exception Room",
    "businessProblem": "Rail and corridor exceptions create operational and financial impact that is hard to prove later.",
    "painSignal": "Kumba's Q2 2026 report says sales were affected by a planned Transnet logistics maintenance shutdown, while operational/logistics momentum was improving.",
    "latestActivity": "Kumba's Q2 2026 report cited a 1% sales-volume decline, with planned Transnet logistics maintenance affecting volumes, while operational and logistics momentum was improving.",
    "whyNow": "A corridor exception timeline makes operational disruptions defensible against claims and disputes.",
    "personalisation": "Kumba's Q2 2026 report says sales were affected by a planned Transnet logistics maintenance shutdown, while operational/logistics momentum was improving.",
    "trackingCode": "11fig81"
  },
  {
    "id": "NL-0053",
    "company": "Exxaro",
    "website": "https://exxaro.com",
    "industry": "Mining / bulk export",
    "jobTitle": "CEO",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Coal Corridor Exception Room",
    "businessProblem": "Coal movements need clear exception timelines and financial impact views.",
    "painSignal": "The mapping identifies the same sector-specific evidence-room pattern for Exxaro.",
    "latestActivity": "Exxaro's leadership page currently lists Caroline Shirindza as Executive Head: Coal, with digitalisation and supply-chain/business-improvement experience.",
    "whyNow": "The prototype should connect coal exceptions with evidence and operational impact rather than generic AI.",
    "personalisation": "The mapping identifies the same sector-specific evidence-room pattern for Exxaro.",
    "trackingCode": "1i4ss64"
  },
  {
    "id": "NL-0054",
    "company": "Thungela",
    "website": "https://www.thungela.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Chief Operations Officer",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Coal Rail Exception Room",
    "businessProblem": "Rail and export exceptions need time-aligned operational evidence.",
    "painSignal": "Thungela published a May 2026 regulatory notice naming Johan van Schalkwyk as COO and documenting an officer transaction.",
    "latestActivity": "Thungela's official leadership page currently identifies Johan van Schalkwyk as COO; a 2026 SENS notice also names him in that role.",
    "whyNow": "The prototype can connect operational events to corridor evidence rather than dashboards alone.",
    "personalisation": "Thungela published a May 2026 regulatory notice naming Johan van Schalkwyk as COO and documenting an officer transaction.",
    "trackingCode": "1591bek"
  },
  {
    "id": "NL-0055",
    "company": "Grindrod",
    "website": "https://www.grindrod.com",
    "industry": "Logistics / rail",
    "jobTitle": "Executive / Rail Solutions",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Rail Corridor Evidence Room",
    "businessProblem": "Rail expansion creates a need for corridor exception intelligence and evidence.",
    "painSignal": "Grindrod announced Siyanda Mba as CEO: Rail Solutions effective 1 Oct 2026; company also announced strong 2026 interim performance.",
    "latestActivity": "Grindrod announced Siyanda Mba as CEO: Rail Solutions effective 1 October 2026 and published strong 2026 interim results.",
    "whyNow": "A corridor evidence layer aligns with current rail growth and performance focus.",
    "personalisation": "Grindrod announced Siyanda Mba as CEO: Rail Solutions effective 1 Oct 2026; company also announced strong 2026 interim performance.",
    "trackingCode": "0v7hdkh"
  },
  {
    "id": "NL-0056",
    "company": "FlySafair",
    "website": "https://www.flysafair.co.za",
    "industry": "Aviation",
    "jobTitle": "Customer Support / Operations",
    "solution": "AI Employee",
    "prototypeName": "Flight Support Triage Employee",
    "businessProblem": "Booking and disruption enquiries require triage, status information and human handoff.",
    "painSignal": "FlySafair updated its booking help desk in Aug 2026 and current app feedback highlights booking / boarding-pass issues.",
    "latestActivity": "FlySafair updated its online booking help content in August 2026; current customer feedback also references booking/session issues and flight-status improvements.",
    "whyNow": "A support employee can resolve routine questions while escalating disruption-sensitive cases.",
    "personalisation": "FlySafair updated its booking help desk in Aug 2026 and current app feedback highlights booking / boarding-pass issues.",
    "trackingCode": "087k3mn"
  },
  {
    "id": "NL-0057",
    "company": "FNB Life",
    "website": "https://www.fnb.co.za",
    "industry": "Financial services / insurance",
    "jobTitle": "Claims Operations",
    "solution": "AI Employee",
    "prototypeName": "Claims Intake & Chasing Employee",
    "businessProblem": "Claims require intake, document completeness and follow-up.",
    "painSignal": "The mapping identifies claims intake + document completeness + chasing.",
    "latestActivity": "Current prospect mapping: claims intake, chasing and audit trail.",
    "whyNow": "A bounded claims workflow is a good AI employee candidate with clear audit requirements.",
    "personalisation": "The mapping identifies claims intake + document completeness + chasing.",
    "trackingCode": "00pf6vq"
  },
  {
    "id": "NL-0058",
    "company": "IGrow Wealth",
    "website": "https://igrow.co.za",
    "industry": "Property / wealth services",
    "jobTitle": "Operations / AI hiring",
    "solution": "AI Employee",
    "prototypeName": "Property Operations Employee",
    "businessProblem": "Property operations contain repetitive admin and customer follow-up.",
    "painSignal": "The mapping notes IGrow advertised an AI call-centre engineer role and a 3CX + Zoho voice layer opportunity.",
    "latestActivity": "Current NahaLabs mapping specifically references an advertised AI call-centre engineer role.",
    "whyNow": "The existing technology intent makes a working AI employee prototype commercially relevant.",
    "personalisation": "The mapping notes IGrow advertised an AI call-centre engineer role and a 3CX + Zoho voice layer opportunity.",
    "trackingCode": "0in38g7"
  },
  {
    "id": "NL-0059",
    "company": "BizLife Medical Accounts",
    "website": "",
    "industry": "Medical billing / admin",
    "jobTitle": "Management",
    "solution": "AI Employee",
    "prototypeName": "Billing Follow-up Autopilot",
    "businessProblem": "Billing follow-up, claims-status nudges and audit work are repetitive.",
    "painSignal": "The mapping references public posts about claims/billing admin load.",
    "latestActivity": "Current prospect mapping: admin autopilot, billing follow-up and audit trail.",
    "whyNow": "An audit-trailed workflow can reduce repetitive admin without making clinical decisions.",
    "personalisation": "The mapping references public posts about claims/billing admin load.",
    "trackingCode": "03of18p"
  },
  {
    "id": "NL-0060",
    "company": "Takealot Group",
    "website": "https://www.takealot.com",
    "industry": "E-commerce / logistics",
    "jobTitle": "Logistics / Operations",
    "solution": "AI Employee",
    "prototypeName": "Logistics Exception Employee",
    "businessProblem": "ETA monitoring and exception communication are repetitive at scale.",
    "painSignal": "The mapping identifies logistics AI employee for ETA monitoring and exception communications.",
    "latestActivity": "Current prospect mapping: logistics ETA and exception communications.",
    "whyNow": "High-volume exception handling is a classic employee-style workflow.",
    "personalisation": "The mapping identifies logistics AI employee for ETA monitoring and exception communications.",
    "trackingCode": "11f0n5s"
  },
  {
    "id": "NL-0061",
    "company": "HAKKI AFRICA",
    "website": "https://hakki.co.za",
    "industry": "Fleet / mobility",
    "jobTitle": "Fleet Operations Lead",
    "solution": "Control Centre",
    "prototypeName": "FleetPulse Control Tower",
    "businessProblem": "Fleet allocation and vehicle operations require a single operational view.",
    "painSignal": "HAKKI's current public team page identifies Dean Goulding as Fleet Operations Lead overseeing vehicle allocation and fleet operations.",
    "latestActivity": "HAKKI's current public team page identifies Dean Goulding as Fleet Operations Lead overseeing vehicle allocation and fleet operations.",
    "whyNow": "The prototype can show how fleet allocation, exceptions and driver support come together in one control tower.",
    "personalisation": "HAKKI's current public team page identifies Dean Goulding as Fleet Operations Lead overseeing vehicle allocation and fleet operations.",
    "trackingCode": "0qa0690"
  },
  {
    "id": "NL-0062",
    "company": "Vodacom Group / Business",
    "website": "https://www.vodacom.co.za/business",
    "industry": "Telecoms",
    "jobTitle": "Business Performance / Margin",
    "solution": "Control Centre",
    "prototypeName": "MarginGuard",
    "businessProblem": "Margin assurance and reporting are fragmented across business operations.",
    "painSignal": "The mapping identifies hiring around margin assurance and reporting.",
    "latestActivity": "Current prospect mapping: MarginGuard / Business Performance Control Centre.",
    "whyNow": "A small control centre can surface margin exceptions without replacing finance systems.",
    "personalisation": "The mapping identifies hiring around margin assurance and reporting.",
    "trackingCode": "06so3y6"
  },
  {
    "id": "NL-0063",
    "company": "Sea Harvest",
    "website": "https://www.seaharvestgroup.co.za",
    "industry": "Food / manufacturing",
    "jobTitle": "Business Systems / Operations",
    "solution": "Control Centre",
    "prototypeName": "Workflow & Automation Control Centre",
    "businessProblem": "Workflow and automation opportunities need a common operational view.",
    "painSignal": "The mapping references a Business Systems Analyst opportunity and an internal workflow/control-centre prototype.",
    "latestActivity": "Current NahaLabs mapping: Business Systems Analyst signal and internal workflow automation control centre.",
    "whyNow": "The prototype can turn scattered workflows into a visible action queue and exception view.",
    "personalisation": "The mapping references a Business Systems Analyst opportunity and an internal workflow/control-centre prototype.",
    "trackingCode": "0bx4lsn"
  },
  {
    "id": "NL-0064",
    "company": "AFGRI Equipment",
    "website": "https://www.afgriequipment.co.za",
    "industry": "Equipment / field service",
    "jobTitle": "Operations / Service",
    "solution": "Control Centre",
    "prototypeName": "JobCard Pulse",
    "businessProblem": "Service job-card progress and exceptions can be difficult to monitor centrally.",
    "painSignal": "The mapping identifies JobCard Pulse.",
    "latestActivity": "Current prospect mapping: JobCard Pulse.",
    "whyNow": "A control centre can expose overdue jobs and exception ownership immediately.",
    "personalisation": "The mapping identifies JobCard Pulse.",
    "trackingCode": "0lseuhp"
  },
  {
    "id": "NL-0065",
    "company": "PartServe",
    "website": "https://www.partserve.co.za",
    "industry": "IT services / field service",
    "jobTitle": "Service Operations",
    "solution": "Control Centre",
    "prototypeName": "Service Command Centre",
    "businessProblem": "Service workload and exception ownership need a common operational view.",
    "painSignal": "The mapping identifies PartServe as a Service Command Centre opportunity.",
    "latestActivity": "Current prospect mapping: Service Command Centre.",
    "whyNow": "Use the prototype to make ageing tickets and operational bottlenecks visible.",
    "personalisation": "The mapping identifies PartServe as a Service Command Centre opportunity.",
    "trackingCode": "0kchalg"
  },
  {
    "id": "NL-0066",
    "company": "Arc International Telecoms",
    "website": "",
    "industry": "Telecoms / field services",
    "jobTitle": "Commercial / Operations",
    "solution": "Control Centre",
    "prototypeName": "Quote-to-Delivery Control Centre",
    "businessProblem": "Quotes can become disconnected from delivery execution.",
    "painSignal": "The mapping identifies a quote-to-delivery control centre.",
    "latestActivity": "Current prospect mapping: quote-to-delivery control centre.",
    "whyNow": "The prototype shows commercial-to-operational continuity rather than another CRM.",
    "personalisation": "The mapping identifies a quote-to-delivery control centre.",
    "trackingCode": "0eg3azn"
  },
  {
    "id": "NL-0067",
    "company": "Designer Water SA",
    "website": "https://designerwater.com",
    "industry": "Water / field service",
    "jobTitle": "Founder",
    "solution": "Control Centre",
    "prototypeName": "POD Control Tower",
    "businessProblem": "Proof-of-delivery and field service evidence need a clear operational view.",
    "painSignal": "Public research found John Thompson's email only in a low-confidence directory; company page lists info@designerwater.com.",
    "latestActivity": "Latest research confirmed only low-confidence public email data; company website uses a role inbox.",
    "whyNow": "A POD control tower is directly tied to field-service proof and operational handover.",
    "personalisation": "Public research found John Thompson's email only in a low-confidence directory; company page lists info@designerwater.com.",
    "trackingCode": "150lv28"
  },
  {
    "id": "NL-0068",
    "company": "Capitec",
    "website": "https://www.capitecbank.co.za",
    "industry": "Banking",
    "jobTitle": "Business Client Experience",
    "solution": "Control Centre",
    "prototypeName": "Business Client Action Hub",
    "businessProblem": "Client operations need prioritised actions rather than static reporting.",
    "painSignal": "The mapping identifies a Business Client Experience Action Hub.",
    "latestActivity": "Current prospect mapping: business client experience action hub.",
    "whyNow": "A focused action hub can surface exceptions and recommended next steps for relationship teams.",
    "personalisation": "The mapping identifies a Business Client Experience Action Hub.",
    "trackingCode": "0ewtzf1"
  },
  {
    "id": "NL-0069",
    "company": "Citadel Investment Services",
    "website": "https://www.citadel.co.za",
    "industry": "Wealth management",
    "jobTitle": "Client Operations",
    "solution": "Control Centre",
    "prototypeName": "Client Operations Control Centre",
    "businessProblem": "Client operations involve recurring action queues and exceptions.",
    "painSignal": "The mapping identifies a Client Operations Control Centre.",
    "latestActivity": "Current prospect mapping: client operations control centre.",
    "whyNow": "A control centre can make the operational backlog and handoffs explicit.",
    "personalisation": "The mapping identifies a Client Operations Control Centre.",
    "trackingCode": "14v998t"
  },
  {
    "id": "NL-0070",
    "company": "RAiN Chartered Accountants",
    "website": "",
    "industry": "Accounting",
    "jobTitle": "Audit / Operations",
    "solution": "Control Centre",
    "prototypeName": "Audit & Exception Control Hub",
    "businessProblem": "Audit exceptions and client follow-up require structured ownership.",
    "painSignal": "The mapping identifies an Audit and Exception Control Hub.",
    "latestActivity": "Current prospect mapping: audit and exception control hub.",
    "whyNow": "Make audit exceptions visible and assignable instead of spreadsheet-only tracking.",
    "personalisation": "The mapping identifies an Audit and Exception Control Hub.",
    "trackingCode": "1sabwyk"
  },
  {
    "id": "NL-0071",
    "company": "Vinet Internet Solutions",
    "website": "https://www.vinet.co.za",
    "industry": "Internet / NOC",
    "jobTitle": "Service Delivery",
    "solution": "Control Centre",
    "prototypeName": "Service Delivery & NOC Control Centre",
    "businessProblem": "Service delivery and NOC events need exception visibility and ownership.",
    "painSignal": "The mapping identifies a service delivery and NOC control centre.",
    "latestActivity": "Current prospect mapping: service delivery / NOC control centre.",
    "whyNow": "A central view can reduce time lost moving between tickets, alerts and customer context.",
    "personalisation": "The mapping identifies a service delivery and NOC control centre.",
    "trackingCode": "17hvap2"
  },
  {
    "id": "NL-0072",
    "company": "Hydraform",
    "website": "https://www.hydraform.com",
    "industry": "Manufacturing / construction",
    "jobTitle": "Sales / Operations",
    "solution": "Control Centre",
    "prototypeName": "DealFlow Command Centre",
    "businessProblem": "Deals, quotations and operational follow-through can become fragmented.",
    "painSignal": "The mapping identifies DealFlow Command Centre.",
    "latestActivity": "Current prospect mapping: deal-flow command centre.",
    "whyNow": "A lightweight command centre can expose stalled deals and next actions.",
    "personalisation": "The mapping identifies DealFlow Command Centre.",
    "trackingCode": "1l6tpo3"
  },
  {
    "id": "NL-0073",
    "company": "Bowmans",
    "website": "https://www.bowmanslaw.com",
    "industry": "Legal",
    "jobTitle": "Matter Operations",
    "solution": "Control Centre",
    "prototypeName": "MatterTime Hub",
    "businessProblem": "Matter time, tasks and exceptions need operational visibility.",
    "painSignal": "The mapping identifies MatterTime Hub.",
    "latestActivity": "Current prospect mapping: matter-time hub.",
    "whyNow": "A focused internal prototype can show time leakage and unowned next actions.",
    "personalisation": "The mapping identifies MatterTime Hub.",
    "trackingCode": "1cstjco"
  },
  {
    "id": "NL-0074",
    "company": "Apex Cordset",
    "website": "",
    "industry": "Manufacturing",
    "jobTitle": "Operations",
    "solution": "Control Centre",
    "prototypeName": "ApexLeave Hub",
    "businessProblem": "Leave and staffing events can affect operational coverage.",
    "painSignal": "The mapping identifies ApexLeave Hub.",
    "latestActivity": "Current prospect mapping: ApexLeave Hub.",
    "whyNow": "The prototype should show staffing risk rather than generic HR software.",
    "personalisation": "The mapping identifies ApexLeave Hub.",
    "trackingCode": "07p3svz"
  },
  {
    "id": "NL-0075",
    "company": "DAS Construction",
    "website": "",
    "industry": "Construction",
    "jobTitle": "Site Operations",
    "solution": "Control Centre",
    "prototypeName": "SiteSync Industrial",
    "businessProblem": "Site execution requires task, issue and handover visibility.",
    "painSignal": "The mapping identifies SiteSync Industrial.",
    "latestActivity": "Current prospect mapping: site-sync industrial control centre.",
    "whyNow": "A field control centre can reduce time lost chasing site updates.",
    "personalisation": "The mapping identifies SiteSync Industrial.",
    "trackingCode": "07aadok"
  },
  {
    "id": "NL-0076",
    "company": "Broll",
    "website": "https://www.broll.com",
    "industry": "Property services",
    "jobTitle": "Property Operations",
    "solution": "Control Centre",
    "prototypeName": "LeasePulse",
    "businessProblem": "Lease and property workflows need clear exception ownership.",
    "painSignal": "The mapping says Broll should only be targeted after fresh evidence.",
    "latestActivity": "Current NahaLabs mapping explicitly requires fresh evidence before outreach.",
    "whyNow": "Do not outreach until a fresh trigger is independently verified.",
    "personalisation": "The mapping says Broll should only be targeted after fresh evidence.",
    "trackingCode": "1vakbtt"
  },
  {
    "id": "NL-0077",
    "company": "Kumba Iron Ore",
    "website": "https://www.angloamericankumba.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Chief Executive",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Iron Ore Corridor Exception Room",
    "businessProblem": "Rail exceptions need time-aligned evidence and financial context.",
    "painSignal": "Q2 2026 report cited Transnet logistics maintenance as a factor affecting sales volumes.",
    "latestActivity": "Kumba's Q2 2026 report cited a 1% sales-volume decline, with planned Transnet logistics maintenance affecting volumes, while operational and logistics momentum was improving.",
    "whyNow": "A corridor timeline can make operational disruption evidence defensible.",
    "personalisation": "Q2 2026 report cited Transnet logistics maintenance as a factor affecting sales volumes.",
    "trackingCode": "1usd1qg"
  },
  {
    "id": "NL-0078",
    "company": "Kumba Iron Ore",
    "website": "https://www.angloamericankumba.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Executive / Operations",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Iron Ore Corridor Exception Room",
    "businessProblem": "Rail exceptions need time-aligned evidence and financial context.",
    "painSignal": "Q2 2026 report cited Transnet logistics maintenance as a factor affecting sales volumes.",
    "latestActivity": "Kumba's Q2 2026 report cited a 1% sales-volume decline, with planned Transnet logistics maintenance affecting volumes, while operational and logistics momentum was improving.",
    "whyNow": "A corridor timeline can make operational disruption evidence defensible.",
    "personalisation": "Q2 2026 report cited Transnet logistics maintenance as a factor affecting sales volumes.",
    "trackingCode": "1defzu9"
  },
  {
    "id": "NL-0079",
    "company": "Exxaro",
    "website": "https://exxaro.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Executive Head: Coal",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Coal Corridor Exception Room",
    "businessProblem": "Coal movement exceptions need operational evidence tied to impact.",
    "painSignal": "Current Exxaro leadership page identifies Caroline Shirindza as Executive Head: Coal with digitalisation and supply-chain experience.",
    "latestActivity": "Exxaro's leadership page currently lists Caroline Shirindza as Executive Head: Coal, with digitalisation and supply-chain/business-improvement experience.",
    "whyNow": "A prototype can align coal exceptions with evidence and operational decision-making.",
    "personalisation": "Current Exxaro leadership page identifies Caroline Shirindza as Executive Head: Coal with digitalisation and supply-chain experience.",
    "trackingCode": "0e0l4z0"
  },
  {
    "id": "NL-0080",
    "company": "Thungela",
    "website": "https://www.thungela.com",
    "industry": "Mining / bulk export",
    "jobTitle": "Operations / Executive",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Coal Rail Exception Room",
    "businessProblem": "Rail and export exceptions need time-aligned operational evidence.",
    "painSignal": "Official Thungela leadership material confirms the COO and coal operations context.",
    "latestActivity": "Thungela's official leadership page currently identifies Johan van Schalkwyk as COO; a 2026 SENS notice also names him in that role.",
    "whyNow": "The prototype can turn rail exceptions into a defensible sequence of evidence.",
    "personalisation": "Official Thungela leadership material confirms the COO and coal operations context.",
    "trackingCode": "0d5xiyx"
  }
];
export function getProspect(id:string){return prospects.find(p=>p.id.toLowerCase()===id.toLowerCase());}
