export type Prospect = {
  id: string;
  company: string;
  website: string;
  industry: string;
  firstName: string;
  lastName: string;
  jobTitle: string;
  decisionMaker: string;
  email: string;
  emailStatus: string;
  solution: string;
  prototypeName: string;
  businessProblem: string;
  painSignal: string;
  latestActivity: string;
  activityDate: string;
  activitySource: string;
  activityEvidence: string;
  whyNow: string;
  personalisation: string;
  trackingCode: string;
};

export const prospects: Prospect[] = [
  {
    "id": "NL-0001",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "JBC Roof Cover",
    "website": "https://jbcroofcover.co.za",
    "industry": "Roofing / home services",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Ops Manager",
    "decisionMaker": "Owner / Ops Manager",
    "email": "jbc@roofcover.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "JBC Enquiry Recovery Centre",
    "businessProblem": "Roof-leak enquiries can become slow, unstructured WhatsApp conversations.",
    "painSignal": "Public positioning includes roof-repair enquiries and a strong local service footprint; the outreach brief identified photo-first leak qualification and missed-lead recovery.",
    "latestActivity": "Current prospect mapping: rainy-season urgent enquiries; photo-first roof-leak qualification proposed.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Urgent service demand is time-sensitive; faster qualification is directly tied to booking conversion.",
    "personalisation": "Public positioning includes roof-repair enquiries and a strong local service footprint; the outreach brief identified photo-first leak qualification and missed-lead recovery.",
    "trackingCode": "1yphi9z1g3"
  },
  {
    "id": "NL-0002",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "S60 Rapid Plumbing",
    "website": "https://s60rapid-plumbing.co.za",
    "industry": "Plumbing",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Director / Owner",
    "decisionMaker": "Director / Owner",
    "email": "info@s60rapid-plumbing.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "24/7 Plumbing Triage Centre",
    "businessProblem": "Emergency enquiries arrive outside office hours and need rapid routing.",
    "painSignal": "The outreach brief specifically identifies 24/7 emergency triage and booking as the clearest workflow.",
    "latestActivity": "Current prospect mapping: demand outside office hours.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Emergency leads decay quickly when response is delayed.",
    "personalisation": "The outreach brief specifically identifies 24/7 emergency triage and booking as the clearest workflow.",
    "trackingCode": "1km79gw0ip"
  },
  {
    "id": "NL-0003",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Supa Nova Electrical, Plumbing and Solar",
    "website": "https://supanova.co.za",
    "industry": "Electrical / plumbing / solar",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Ops Manager",
    "decisionMaker": "Owner / Ops Manager",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Dual-Trade Lead Qualification",
    "businessProblem": "Different service lines require different qualification paths.",
    "painSignal": "The outreach brief identifies dual-trade qualification plus solar lead scoring.",
    "latestActivity": "Current prospect mapping: multi-service qualifier and solar lead scoring.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A single structured intake can stop mixed enquiries from reaching the wrong team.",
    "personalisation": "The outreach brief identifies dual-trade qualification plus solar lead scoring.",
    "trackingCode": "1iyz21m096"
  },
  {
    "id": "NL-0004",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Roof Guys",
    "website": "https://roofguys.co.za",
    "industry": "Roofing",
    "firstName": "",
    "lastName": "Sean",
    "jobTitle": "",
    "decisionMaker": "Sean",
    "email": "info@roofguys.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Roof Quote Qualifier",
    "businessProblem": "Quote requests need roof photos, location and scope before a useful estimate.",
    "painSignal": "The outreach brief calls out photo + location + estimate qualification; contact research currently only identifies Sean by first name.",
    "latestActivity": "Current prospect mapping: Sandton roofing enquiry qualification.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "High-value home-service leads benefit from fewer back-and-forth messages.",
    "personalisation": "The outreach brief calls out photo + location + estimate qualification; contact research currently only identifies Sean by first name.",
    "trackingCode": "1tdjv261su"
  },
  {
    "id": "NL-0005",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Randburg Auto Repairs",
    "website": "https://randburgautorepairs.co.za",
    "industry": "Automotive services",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner",
    "decisionMaker": "Owner",
    "email": "info@randburgautorepairs.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "After-Hours Auto Enquiry Desk",
    "businessProblem": "Breakdown and diagnostic enquiries arrive after hours.",
    "painSignal": "The outreach brief identifies WhatsApp being office-hours only and recommends after-hours triage + diagnostic booking.",
    "latestActivity": "Current prospect mapping: after-hours breakdown triage.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Breakdown demand is immediate and can move to competitors when response is slow.",
    "personalisation": "The outreach brief identifies WhatsApp being office-hours only and recommends after-hours triage + diagnostic booking.",
    "trackingCode": "0va13qs1q6"
  },
  {
    "id": "NL-0006",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Bliss Renovations",
    "website": "https://blissrenovations.co.za",
    "industry": "Renovations",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner",
    "decisionMaker": "Owner",
    "email": "info@blissrenovations.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Renovation Scope & Site Visit Desk",
    "businessProblem": "Renovation enquiries need scope, budget and site-visit qualification.",
    "painSignal": "Public contact research found a Gmail address but did not establish that it belongs to the owner.",
    "latestActivity": "Personal email not safely attributable; use the business inbox only after confirmation.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Personal-email-research-6-Oct-3f10c662fcb0814d8022e6c909240c02",
    "activityEvidence": "Public contact page lists business contact plus a Gmail address not tied to the owner.",
    "whyNow": "A structured scope intake can reduce admin before site visits.",
    "personalisation": "Public contact research found a Gmail address but did not establish that it belongs to the owner.",
    "trackingCode": "1lxcn2d1ys"
  },
  {
    "id": "NL-0007",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Prime Secure",
    "website": "",
    "industry": "Security / locksmith",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Operations",
    "decisionMaker": "Owner / Operations",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need immediate triage and dispatch.",
    "painSignal": "The solution mapping groups Prime Secure with HTC and Goldman Locksmiths for 24/7 emergency triage.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Emergency-response workflows are a strong fit for structured WhatsApp intake.",
    "personalisation": "The solution mapping groups Prime Secure with HTC and Goldman Locksmiths for 24/7 emergency triage.",
    "trackingCode": "1y27tou1m5"
  },
  {
    "id": "NL-0008",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "HTC Locksmiths",
    "website": "",
    "industry": "Locksmith",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Operations",
    "decisionMaker": "Owner / Operations",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need location, urgency and access details.",
    "painSignal": "The solution mapping groups HTC with Prime Secure and Goldman Locksmiths for 24/7 emergency triage.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Fast routing is the business outcome; not another chatbot.",
    "personalisation": "The solution mapping groups HTC with Prime Secure and Goldman Locksmiths for 24/7 emergency triage.",
    "trackingCode": "0uwv6qp0cx"
  },
  {
    "id": "NL-0009",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Goldman Locksmiths",
    "website": "",
    "industry": "Locksmith",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Operations",
    "decisionMaker": "Owner / Operations",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Emergency Dispatch Intake",
    "businessProblem": "Emergency service requests need location, urgency and access details.",
    "painSignal": "The solution mapping identifies a 24/7 emergency triage + dispatch intake.",
    "latestActivity": "Current prospect mapping: 24/7 emergency dispatch intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Immediate routing protects response time and booking conversion.",
    "personalisation": "The solution mapping identifies a 24/7 emergency triage + dispatch intake.",
    "trackingCode": "1ir98vh1eo"
  },
  {
    "id": "NL-0010",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "JMT Handyman",
    "website": "https://jmthandymanservices.co.za",
    "industry": "Handyman",
    "firstName": "",
    "lastName": "John",
    "jobTitle": "Owner",
    "decisionMaker": "John",
    "email": "info@jmthandymanservices.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "JMT Quote Recovery Desk",
    "businessProblem": "Service and area qualification plus after-hours quote recovery are currently manual.",
    "painSignal": "The outreach brief says the business sells WhatsApp quotes and 30–60 minute response; personal email was not publicly found.",
    "latestActivity": "Current prospect mapping: service/area/urgency qualifier and after-hours recovery.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A deterministic intake can protect the 30–60 minute response promise.",
    "personalisation": "The outreach brief says the business sells WhatsApp quotes and 30–60 minute response; personal email was not publicly found.",
    "trackingCode": "1la3d2j1bi"
  },
  {
    "id": "NL-0011",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Etchells and Young Property Brokers",
    "website": "https://www.etchellsandyoung.co.za",
    "industry": "Property / real estate",
    "firstName": "Jackie",
    "lastName": "Roux",
    "jobTitle": "Property Broker",
    "decisionMaker": "Jackie Roux",
    "email": "jackie@etchellsandyoung.co.za",
    "emailStatus": "Verified Personal",
    "solution": "Lead Machine",
    "prototypeName": "Rental Pre-Qualification Desk",
    "businessProblem": "Rental leads need qualification and viewing scheduling before agent time is consumed.",
    "painSignal": "Direct personal email verified on the company site.",
    "latestActivity": "Latest research confirms public profile and direct work email.",
    "activityDate": "2026-10-06",
    "activitySource": "https://www.etchellsandyoung.co.za/jackie-roux",
    "activityEvidence": "Public company profile.",
    "whyNow": "Property leads can be qualified before viewing slots are committed.",
    "personalisation": "Direct personal email verified on the company site.",
    "trackingCode": "13cwal60hm"
  },
  {
    "id": "NL-0012",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Etchells and Young Property Brokers",
    "website": "https://www.etchellsandyoung.co.za",
    "industry": "Property / real estate",
    "firstName": "Marius",
    "lastName": "Bezuidenhout",
    "jobTitle": "Property Broker",
    "decisionMaker": "Marius Bezuidenhout",
    "email": "marius@etchellsandyoung.co.za",
    "emailStatus": "Verified Personal",
    "solution": "Lead Machine",
    "prototypeName": "Rental Pre-Qualification Desk",
    "businessProblem": "Rental leads need qualification and viewing scheduling before agent time is consumed.",
    "painSignal": "Direct personal email verified on the company site.",
    "latestActivity": "Latest research confirms public profile and direct work email.",
    "activityDate": "2026-10-06",
    "activitySource": "https://www.etchellsandyoung.co.za/marius-bezuidenhout",
    "activityEvidence": "Public company profile.",
    "whyNow": "Property leads can be qualified before viewing slots are committed.",
    "personalisation": "Direct personal email verified on the company site.",
    "trackingCode": "03w7fb30vt"
  },
  {
    "id": "NL-0013",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Blakes Maphanga Attorneys",
    "website": "https://blakes.co.za",
    "industry": "Legal",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Managing Partner / Director",
    "decisionMaker": "Managing Partner / Director",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Legal Intake & Routing",
    "businessProblem": "Legal enquiries require structured intake and routing rather than long free-text email chains.",
    "painSignal": "Public contact page lists several directors' own emails but does not identify the Managing Partner.",
    "latestActivity": "Latest research found Feyoena Hammann, Lindie Burger, Eugene Meyer and Phethelo Fakude as public directors; exact target contact is not confirmed.",
    "activityDate": "2026-10-06",
    "activitySource": "https://blakes.co.za/contact/",
    "activityEvidence": "Public company contact page.",
    "whyNow": "The right prototype is a structured intake and routing layer; do not guess the decision-maker email.",
    "personalisation": "Public contact page lists several directors' own emails but does not identify the Managing Partner.",
    "trackingCode": "1ot6v310nq"
  },
  {
    "id": "NL-0014",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Melrose Dental Studio",
    "website": "https://melrosedental.co.za",
    "industry": "Dental",
    "firstName": "Edwin",
    "lastName": "Alberts",
    "jobTitle": "Dentist / Owner",
    "decisionMaker": "Edwin Alberts",
    "email": "info@melrosedental.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Dental Treatment Intent Desk",
    "businessProblem": "Treatment intent needs triage and fast WhatsApp booking.",
    "painSignal": "The outreach mapping identifies treatment-intent triage + WhatsApp booking.",
    "latestActivity": "Current prospect mapping: treatment-intent triage and booking.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "High-intent dental enquiries can be lost between first message and booking.",
    "personalisation": "The outreach mapping identifies treatment-intent triage + WhatsApp booking.",
    "trackingCode": "03h578v1tg"
  },
  {
    "id": "NL-0015",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Mission Mobile",
    "website": "https://missionmobile.co.za",
    "industry": "Mobile / retail",
    "firstName": "Tim",
    "lastName": "Strike",
    "jobTitle": "Commercial / Owner",
    "decisionMaker": "Tim Strike",
    "email": "sales@missionmobile.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Retail Enquiry Qualification",
    "businessProblem": "Product and service enquiries need structured qualification before follow-up.",
    "painSignal": "The solution mapping identifies a retail enquiry Lead Machine.",
    "latestActivity": "Current prospect mapping: retail enquiry qualification.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A lightweight intake can route high-intent retail enquiries to the right person.",
    "personalisation": "The solution mapping identifies a retail enquiry Lead Machine.",
    "trackingCode": "1pd62bj0tv"
  },
  {
    "id": "NL-0016",
    "sourceWorkbook": "JBC Roof Cover and other prospects",
    "company": "Inospace",
    "website": "https://inospace.com",
    "industry": "Flexible workspace / property",
    "firstName": "Rael",
    "lastName": "Levitt",
    "jobTitle": "Founder / Executive",
    "decisionMaker": "Rael Levitt",
    "email": "grow@inospace.com",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "SME Fulfilment Acquisition Desk",
    "businessProblem": "SME acquisition enquiries need structured qualification and routing.",
    "painSignal": "The solution mapping identifies SME fulfilment acquisition as the Lead Machine use case.",
    "latestActivity": "Current prospect mapping: Lead Machine for SME fulfilment acquisition.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A fast qualification layer can reduce sales admin across multiple enquiry sources.",
    "personalisation": "The solution mapping identifies SME fulfilment acquisition as the Lead Machine use case.",
    "trackingCode": "0n72wvo1on"
  },
  {
    "id": "NL-0017",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Cassims and Co",
    "website": "https://www.cassimsandco.co.za",
    "industry": "Jewellery",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Management",
    "decisionMaker": "Owner / Management",
    "email": "info@cassimsandco.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Jewellery Enquiry Continuity Desk",
    "businessProblem": "Enquiry continuity can break when client relationships sit with one designer.",
    "painSignal": "The outreach mapping explicitly notes lost continuity when a designer left.",
    "latestActivity": "Current prospect mapping: Tier A jewellery intake pack.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "The prototype can preserve client context and enquiry continuity without replacing the team.",
    "personalisation": "The outreach mapping explicitly notes lost continuity when a designer left.",
    "trackingCode": "0jqfyrb095"
  },
  {
    "id": "NL-0018",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Alloy Jewellery Gallery",
    "website": "https://alloygallery.co.za",
    "industry": "Jewellery",
    "firstName": "Edna",
    "lastName": "",
    "jobTitle": "Owner",
    "decisionMaker": "Edna",
    "email": "edna@alloygallery.co.za",
    "emailStatus": "Verified Personal",
    "solution": "Lead Machine",
    "prototypeName": "Jewellery AI-Assist Desk",
    "businessProblem": "A one-person owner can become the bottleneck for enquiries and follow-up.",
    "painSignal": "Direct owner email verified from public company/industry sources.",
    "latestActivity": "Latest research confirms Edna as owner with public direct email.",
    "activityDate": "2026-10-06",
    "activitySource": "https://alloygallery.co.za/pages/contact",
    "activityEvidence": "Public contact page / industry directory.",
    "whyNow": "Reducing owner-only enquiry handling is the clearest operational wedge.",
    "personalisation": "Direct owner email verified from public company/industry sources.",
    "trackingCode": "0dnm8al1j7"
  },
  {
    "id": "NL-0019",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Skin Reform",
    "website": "https://skinreform.co.za",
    "industry": "Aesthetic / medical",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Clinic / Medical Team",
    "decisionMaker": "Clinic / Medical Team",
    "email": "info@skinreform.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Aesthetic Treatment Intake",
    "businessProblem": "Branch conversion visibility and safe qualification need structured intake.",
    "painSignal": "The mapping specifies an HPCSA-guardrailed aesthetic/medical intake pack, Tier A.",
    "latestActivity": "Current prospect mapping: branch conversion visibility.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Structured triage can reduce repetitive logistics questions while keeping clinical boundaries clear.",
    "personalisation": "The mapping specifies an HPCSA-guardrailed aesthetic/medical intake pack, Tier A.",
    "trackingCode": "0x0igz20fo"
  },
  {
    "id": "NL-0020",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Arca",
    "website": "https://arca.health",
    "industry": "Aesthetic / medical",
    "firstName": "Ade",
    "lastName": "",
    "jobTitle": "Doctor / Owner",
    "decisionMaker": "Ade",
    "email": "info@arca.health",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Medical Enquiry AI-Assist",
    "businessProblem": "A doctor is answering logistics questions that could be structured before clinical interaction.",
    "painSignal": "The mapping explicitly notes the doctor answering logistics questions.",
    "latestActivity": "Current prospect mapping: AI-Assist intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Route logistics away from clinical time while keeping medical decisions human-led.",
    "personalisation": "The mapping explicitly notes the doctor answering logistics questions.",
    "trackingCode": "1twszz309l"
  },
  {
    "id": "NL-0021",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Interiology",
    "website": "https://interiology.co.za",
    "industry": "Luxury kitchens",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Sales",
    "decisionMaker": "Owner / Sales",
    "email": "info@interiology.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Luxury Kitchen Qualification",
    "businessProblem": "Showroom visits should be preceded by budget and project qualification.",
    "painSignal": "The mapping recommends qualifying budget before showroom visits.",
    "latestActivity": "Current prospect mapping: Tier A luxury-kitchens intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A few structured questions can protect expensive showroom time.",
    "personalisation": "The mapping recommends qualifying budget before showroom visits.",
    "trackingCode": "1gt2j74103"
  },
  {
    "id": "NL-0022",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Sandton Kitchens",
    "website": "https://sandtonkitchens.co.za",
    "industry": "Luxury kitchens",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Sales",
    "decisionMaker": "Owner / Sales",
    "email": "info@sandtonkitchens.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Luxury Kitchen Qualification",
    "businessProblem": "Premium clients expect fast WhatsApp replies and clear project qualification.",
    "painSignal": "The mapping explicitly calls out fast WhatsApp replies.",
    "latestActivity": "Current prospect mapping: Tier A luxury-kitchens intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Speed + prequalification is a clear revenue-protection workflow.",
    "personalisation": "The mapping explicitly calls out fast WhatsApp replies.",
    "trackingCode": "01fmo8i123"
  },
  {
    "id": "NL-0023",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "Prestige Marques",
    "website": "",
    "industry": "Automotive",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Sales",
    "decisionMaker": "Owner / Sales",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Lead Machine",
    "prototypeName": "Automotive Voice Qualification",
    "businessProblem": "High-value vehicle enquiries need triage and voice escalation.",
    "painSignal": "The mapping recommends automotive intake with voice escalation because the current personal line lacks triage.",
    "latestActivity": "Current prospect mapping: Tier A automotive intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "The prototype can separate high-intent buyers from routine questions before escalation.",
    "personalisation": "The mapping recommends automotive intake with voice escalation because the current personal line lacks triage.",
    "trackingCode": "07ph1qq1kk"
  },
  {
    "id": "NL-0024",
    "sourceWorkbook": "Jewellery prospects - Cassims and Co",
    "company": "MG Auto",
    "website": "https://mgauto.co.za",
    "industry": "Automotive",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Owner / Sales",
    "decisionMaker": "Owner / Sales",
    "email": "admin@mgauto.co.za",
    "emailStatus": "Verified Company",
    "solution": "Lead Machine",
    "prototypeName": "Vehicle Fit Qualification",
    "businessProblem": "Model, inventory and budget fit need to be captured before follow-up.",
    "painSignal": "The mapping specifies model + inventory + budget fit check.",
    "latestActivity": "Current prospect mapping: Tier A automotive intake.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A structured buyer fit check makes sales follow-up more focused.",
    "personalisation": "The mapping specifies model + inventory + budget fit check.",
    "trackingCode": "1ss5lyd1l9"
  },
  {
    "id": "NL-0025",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "The Baron Group",
    "website": "https://www.thebaron.co.za",
    "industry": "Restaurants / hospitality",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Group Management",
    "decisionMaker": "Group Management",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Revenue & Retention Centre",
    "businessProblem": "Multi-site ordering and customer intelligence are fragmented across venues.",
    "painSignal": "Existing NahaLabs mapping identifies a multi-site ordering + central customer intelligence use case; current website shows multiple branches and ongoing events/promotions.",
    "latestActivity": "Current public website shows multiple branches with active events/promotions; NahaLabs already has a live pilot mapping with the group.",
    "activityDate": "2026-10-06",
    "activitySource": "https://www.thebaron.co.za/",
    "activityEvidence": "Current website shows multi-branch footprint and active promotions.",
    "whyNow": "Multi-site consistency makes centralised WhatsApp/customer intelligence more valuable.",
    "personalisation": "Existing NahaLabs mapping identifies a multi-site ordering + central customer intelligence use case; current website shows multiple branches and ongoing events/promotions.",
    "trackingCode": "1umhmvt0d4"
  },
  {
    "id": "NL-0026",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Hogshead Craft Beer",
    "website": "https://hogshead.co.za",
    "industry": "Restaurants / hospitality",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Group / Venue Management",
    "decisionMaker": "Group / Venue Management",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Flavourly",
    "prototypeName": "Hogshead WhatsApp Retention Desk",
    "businessProblem": "Repeat-customer ordering and retention can be improved through structured WhatsApp.",
    "painSignal": "The mapping identifies ordering + repeat-customer intelligence; the current site publishes menus and loyalty-oriented offers.",
    "latestActivity": "Public site currently publishes detailed menu/loyalty content.",
    "activityDate": "2026-10-06",
    "activitySource": "https://hogshead.co.za/wp-content/uploads/2026/01/Hogshead_Drinks-Menu.pdf",
    "activityEvidence": "Current published menu / loyalty offer material.",
    "whyNow": "A retention layer can turn existing menu and loyalty intent into measurable repeat ordering.",
    "personalisation": "The mapping identifies ordering + repeat-customer intelligence; the current site publishes menus and loyalty-oriented offers.",
    "trackingCode": "0pghzjj0a5"
  },
  {
    "id": "NL-0027",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Cafe Caprice",
    "website": "https://www.cafecaprice.co.za",
    "industry": "Restaurants / hospitality",
    "firstName": "",
    "lastName": "Henry",
    "jobTitle": "Venue Management",
    "decisionMaker": "Henry",
    "email": "reservations@cafecaprice.co.za",
    "emailStatus": "Verified Company",
    "solution": "Flavourly",
    "prototypeName": "Reservations & Tourist Re-Engagement Desk",
    "businessProblem": "Reservation and tourist re-engagement can be lost across busy service periods.",
    "painSignal": "Current public site lists reservations and an active event calendar.",
    "latestActivity": "Recent September 2026 event programming and reservations indicate active venue/event operations.",
    "activityDate": "2026-09-05",
    "activitySource": "https://www.foodyas.com/ZA/Cape-Town/209965050593/Cafe-Caprice",
    "activityEvidence": "Recent public event listing.",
    "whyNow": "High event activity creates a strong case for automated reservation handling and post-visit re-engagement.",
    "personalisation": "Current public site lists reservations and an active event calendar.",
    "trackingCode": "16u7bv60ih"
  },
  {
    "id": "NL-0029",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Bravo Pizzeria Hatfield",
    "website": "",
    "industry": "Restaurants / hospitality",
    "firstName": "",
    "lastName": "Dean",
    "jobTitle": "Owner",
    "decisionMaker": "Dean",
    "email": "deanbravo@gmail.com",
    "emailStatus": "Verified Company",
    "solution": "Flavourly",
    "prototypeName": "Pizzeria Order Recovery Desk",
    "businessProblem": "Ordering, reorder and abandoned-order recovery can be handled through WhatsApp.",
    "painSignal": "The mapping identifies ordering + reorder + abandoned-order recovery.",
    "latestActivity": "Public business Gmail is available but is not a verified office/personal work address.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Personal-email-research-6-Oct-3f10c662fcb0814d8022e6c909240c02",
    "activityEvidence": "6-Oct email research notes deanbravo@gmail.com as public business Gmail.",
    "whyNow": "Do not treat the Gmail address as personal work email.",
    "personalisation": "The mapping identifies ordering + reorder + abandoned-order recovery.",
    "trackingCode": "0mbcpg4091"
  },
  {
    "id": "NL-0030",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Woolworths Food Services",
    "website": "https://www.woolworths.co.za",
    "industry": "Food services",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Corporate / Business Services",
    "decisionMaker": "Corporate / Business Services",
    "email": "CorporateSales@woolworths.co.za",
    "emailStatus": "Verified Company",
    "solution": "Flavourly",
    "prototypeName": "New-Site WhatsApp Ordering Pilot",
    "businessProblem": "New-site food operations create a repeatable WhatsApp revenue workflow opportunity.",
    "painSignal": "The mapping identifies a pilot for new sites.",
    "latestActivity": "Current prospect mapping: new-site pilot.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A repeatable pilot can demonstrate the system before broader rollout.",
    "personalisation": "The mapping identifies a pilot for new sites.",
    "trackingCode": "0zvfy8v1rp"
  },
  {
    "id": "NL-0031",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "SPAR Southern Africa",
    "website": "https://www.spar.co.za",
    "industry": "Retail / food",
    "firstName": "",
    "lastName": "",
    "jobTitle": "",
    "decisionMaker": "SPAR Southern Africa",
    "email": "intcontact@spar.co.za",
    "emailStatus": "Verified Company",
    "solution": "Flavourly",
    "prototypeName": "Demand & Delivery Intelligence Pilot",
    "businessProblem": "Demand and delivery signals are fragmented across a large network.",
    "painSignal": "The mapping identifies a demand/delivery intelligence pilot.",
    "latestActivity": "Current prospect mapping: demand/delivery intelligence pilot.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A focused pilot can show value without replacing existing systems.",
    "personalisation": "The mapping identifies a demand/delivery intelligence pilot.",
    "trackingCode": "039tbv0087"
  },
  {
    "id": "NL-0032",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Hungry Lion",
    "website": "https://www.hungrylion.co.za",
    "industry": "Restaurants / hospitality",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Management",
    "decisionMaker": "Management",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Operations Intelligence",
    "businessProblem": "Restaurant operations create repeatable ordering, customer and retention workflows.",
    "painSignal": "The mapping identifies a restaurant ops layer with Flavourly later.",
    "latestActivity": "Current prospect mapping: restaurant operations layer.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Use the prototype to show one operational loop before asking for a broad deployment.",
    "personalisation": "The mapping identifies a restaurant ops layer with Flavourly later.",
    "trackingCode": "03pjthc0zk"
  },
  {
    "id": "NL-0033",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Pedros Chicken",
    "website": "https://pedroschicken.co.za",
    "industry": "Restaurants / hospitality",
    "firstName": "Peter",
    "lastName": "Erasmus",
    "jobTitle": "Executive / Owner",
    "decisionMaker": "Peter Erasmus",
    "email": "peter@pedroschicken.co.za",
    "emailStatus": "Verified Personal",
    "solution": "Flavourly",
    "prototypeName": "Restaurant Ops & Customer Intelligence",
    "businessProblem": "Multi-channel customer demand creates an opportunity for WhatsApp ordering/ops intelligence.",
    "painSignal": "Peter Erasmus direct work email was found via his own LinkedIn post.",
    "latestActivity": "Public LinkedIn activity from Peter Erasmus provides a direct email and phone contact.",
    "activityDate": "2026-10-06",
    "activitySource": "https://www.linkedin.com/posts/pedros-chicken_calling-all-landlords-and-leasing-agents-activity-7305528016607047681-K6zr",
    "activityEvidence": "His own public LinkedIn post with direct email and phone.",
    "whyNow": "A direct route to the operator makes the prototype-first approach practical.",
    "personalisation": "Peter Erasmus direct work email was found via his own LinkedIn post.",
    "trackingCode": "1byp8960eu"
  },
  {
    "id": "NL-0034",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Life and Brand Portfolio",
    "website": "https://lifeandbrand.co.za",
    "industry": "Hospitality",
    "firstName": "",
    "lastName": "Trevor",
    "jobTitle": "Executive",
    "decisionMaker": "Trevor",
    "email": "info@lifeandbrand.co.za",
    "emailStatus": "Verified Company",
    "solution": "Flavourly",
    "prototypeName": "Venue Booking & Reminder Desk",
    "businessProblem": "A portfolio with many venues and seasonal hiring creates repeatable booking workflows.",
    "painSignal": "The mapping identifies 33 restaurants and seasonal hiring.",
    "latestActivity": "Current prospect mapping: start with one venue and extend after proof.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Pilot in one venue before expanding across the portfolio.",
    "personalisation": "The mapping identifies 33 restaurants and seasonal hiring.",
    "trackingCode": "0j5wp40089"
  },
  {
    "id": "NL-0035",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Twelve Apostles Hotel",
    "website": "https://12apostleshotel.com",
    "industry": "Hospitality",
    "firstName": "Joshua",
    "lastName": "Du Preez",
    "jobTitle": "Operations / Reservations",
    "decisionMaker": "Joshua Du Preez",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "AI Employee",
    "prototypeName": "Hospitality Reservation Employee",
    "businessProblem": "Reservation enquiries, preferences, waitlist and escalation create repetitive front-desk work.",
    "painSignal": "The mapping identifies an AI reservation employee use case.",
    "latestActivity": "Current prospect mapping: reservations, preferences, waitlist and escalation.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "This is a contained AI employee workflow with clear human escalation boundaries.",
    "personalisation": "The mapping identifies an AI reservation employee use case.",
    "trackingCode": "1j0g6w00zs"
  },
  {
    "id": "NL-0036",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "ZDS Recruit",
    "website": "",
    "industry": "Recruitment / hospitality",
    "firstName": "Ryan",
    "lastName": "Roberts",
    "jobTitle": "Founder / Recruiter",
    "decisionMaker": "Ryan Roberts",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "Flavourly",
    "prototypeName": "Recruitment Channel Intelligence",
    "businessProblem": "Recruitment-related bookings/reminders/triage are repetitive and time-sensitive.",
    "painSignal": "The mapping identifies hospitality reservations hiring and recruitment channel intelligence.",
    "latestActivity": "Current prospect mapping: booking/reminders/triage and recruitment channel intelligence.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A prototype can show the workflow end to end before integrating a production ATS.",
    "personalisation": "The mapping identifies hospitality reservations hiring and recruitment channel intelligence.",
    "trackingCode": "1c8teoe04z"
  },
  {
    "id": "NL-0037",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "Positive Freight Solutions",
    "website": "",
    "industry": "Freight / logistics",
    "firstName": "Alex",
    "lastName": "Hill",
    "jobTitle": "Container Division",
    "decisionMaker": "Alex Hill",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "DGT Demurrage Evidence Room",
    "businessProblem": "DGT slot failures create demurrage, waiting time and dispute evidence gaps.",
    "painSignal": "The outreach mapping explicitly cites Alex Hill discussing the DGT slot problem.",
    "latestActivity": "Public industry evidence and the prospect mapping both point to DGT slot/disruption recovery.",
    "activityDate": "2026-09-21",
    "activitySource": "https://www.freightnews.co.za/article/safla-and-rfa-propose-dgt-recovery-compact",
    "activityEvidence": "Industry coverage of DGT recovery efforts and the hidden cost of fragmented operational information.",
    "whyNow": "The prototype can turn a disputed delay into a defensible evidence timeline.",
    "personalisation": "The outreach mapping explicitly cites Alex Hill discussing the DGT slot problem.",
    "trackingCode": "12k2wbf0wu"
  },
  {
    "id": "NL-0038",
    "sourceWorkbook": "Diederick Stopforth - Internet Express and Citi Sprint",
    "company": "Internet Express / Citisprint",
    "website": "",
    "industry": "Logistics / last mile",
    "firstName": "Diederick",
    "lastName": "Stopforth",
    "jobTitle": "Managing Director",
    "decisionMaker": "Diederick Stopforth",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Driver POD Evidence Room",
    "businessProblem": "Rapid growth with owner-drivers can create proof-of-delivery and driver onboarding gaps.",
    "painSignal": "Diederick posted about successfully launching a major international e-commerce account and completing first deliveries.",
    "latestActivity": "Internet Express launched a major international e-commerce account and completed first deliveries; Diederick also promoted an eCommerceLive 2026 session on delivery convenience.",
    "activityDate": "2026-10-03",
    "activitySource": "https://za.linkedin.com/in/diederick-stopforth-b521724",
    "activityEvidence": "Recent LinkedIn activity from Diederick Stopforth and company promotion.",
    "whyNow": "Growth increases the need for structured POD and exception evidence.",
    "personalisation": "Diederick posted about successfully launching a major international e-commerce account and completing first deliveries.",
    "trackingCode": "1tr0v7z1xz"
  },
  {
    "id": "NL-0039",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "Savino Del Bene",
    "website": "https://www.savinodelbene.com",
    "industry": "Freight forwarding",
    "firstName": "Donnaven",
    "lastName": "Parmanand",
    "jobTitle": "Operations / Client",
    "decisionMaker": "Donnaven Parmanand",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "DGT Cancellation Evidence Pack",
    "businessProblem": "Cancelled truck appointments need timestamped evidence and client alerts.",
    "painSignal": "The mapping identifies cancelled DGT truck appointments and dispute timelines.",
    "latestActivity": "Current prospect mapping: cancellation timestamps, client alerts, dispute timelines.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Build evidence at the point of exception instead of after a dispute starts.",
    "personalisation": "The mapping identifies cancelled DGT truck appointments and dispute timelines.",
    "trackingCode": "19el2dp00j"
  },
  {
    "id": "NL-0040",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "Intelligent Security Systems",
    "website": "",
    "industry": "Security / logistics",
    "firstName": "Eugene",
    "lastName": "Kayat",
    "jobTitle": "Management",
    "decisionMaker": "Eugene Kayat",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Incident Evidence Pack",
    "businessProblem": "Timestamped handover evidence and incident packs can strengthen dispute and fraud workflows.",
    "painSignal": "The mapping cites a cargo-fraud article and timestamped evidence use case.",
    "latestActivity": "Current prospect mapping: handover evidence + incident packs.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Evidence quality improves when the timeline is assembled continuously.",
    "personalisation": "The mapping cites a cargo-fraud article and timestamped evidence use case.",
    "trackingCode": "0xa0puf0i5"
  },
  {
    "id": "NL-0041",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "SATI",
    "website": "https://sati.co.za",
    "industry": "Agriculture / exports",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Industry Association",
    "decisionMaker": "Industry Association",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Cold-Chain Evidence Room",
    "businessProblem": "Exporters need defensible cold-chain and port evidence when cargo is delayed.",
    "painSignal": "The mapping identifies cold-chain and port evidence use cases.",
    "latestActivity": "Current prospect mapping: cold-chain and port evidence.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A standard evidence layer can serve many exporters without replacing their operational systems.",
    "personalisation": "The mapping identifies cold-chain and port evidence use cases.",
    "trackingCode": "0mw5vou1nd"
  },
  {
    "id": "NL-0042",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "Hortgro",
    "website": "https://www.hortgro.co.za",
    "industry": "Agriculture / exports",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Industry Association",
    "decisionMaker": "Industry Association",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Cold-Chain Evidence Room",
    "businessProblem": "Exporters need defensible cold-chain and port evidence when cargo is delayed.",
    "painSignal": "The mapping identifies cold-chain and port evidence use cases.",
    "latestActivity": "Current prospect mapping: cold-chain and port evidence.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "Standard evidence can reduce disputes across members.",
    "personalisation": "The mapping identifies cold-chain and port evidence use cases.",
    "trackingCode": "1n1jv3b0y4"
  },
  {
    "id": "NL-0043",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "FPEF",
    "website": "https://fpef.co.za",
    "industry": "Agriculture / exports",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Industry Association",
    "decisionMaker": "Industry Association",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Exporter Evidence Standard",
    "businessProblem": "Exporters need structured evidence across port and cold-chain events.",
    "painSignal": "The mapping identifies cold-chain and port evidence for FPEF and peers.",
    "latestActivity": "Current prospect mapping: export evidence standard.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A shared evidence template can make recurring disputes easier to resolve.",
    "personalisation": "The mapping identifies cold-chain and port evidence for FPEF and peers.",
    "trackingCode": "0u158071px"
  },
  {
    "id": "NL-0044",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "DHL Supply Chain South Africa",
    "website": "https://www.dhl.com/za-en/home/our-divisions/supply-chain.html",
    "industry": "Logistics",
    "firstName": "",
    "lastName": "",
    "jobTitle": "Operations / Supply Chain",
    "decisionMaker": "Operations / Supply Chain",
    "email": "",
    "emailStatus": "Not Found",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Operational Evidence Pilot",
    "businessProblem": "Large operational networks create high-volume exception and handover evidence.",
    "painSignal": "The mapping identifies an operational evidence pilot.",
    "latestActivity": "Current prospect mapping: operational evidence pilot.",
    "activityDate": "2026-10-06",
    "activitySource": "https://app.notion.com/p/Solutions-to-build-per-prospect-3f10c662fcb0815d95faf39b09da9ed2",
    "activityEvidence": "6-Oct outreach solution mapping.",
    "whyNow": "A small evidence pilot can be tested on one exception workflow.",
    "personalisation": "The mapping identifies an operational evidence pilot.",
    "trackingCode": "1mpal4s1fl"
  },
  {
    "id": "NL-0045",
    "sourceWorkbook": "CargoIQ prospecting - Positive Freight Solutions",
    "company": "ATNS",
    "website": "https://www.atns.co.za",
    "industry": "Aviation / public infrastructure",
    "firstName": "Andy",
    "lastName": "Ngubane",
    "jobTitle": "Procurement / Fleet",
    "decisionMaker": "Andy Ngubane",
    "email": "andyn@atns.co.za",
    "emailStatus": "Verified Personal",
    "solution": "CargoIQ / ImpactTrace",
    "prototypeName": "Fleet Contract Assurance Room",
    "businessProblem": "Fleet procurements require clear contract and operational evidence.",
    "painSignal": "ATNS published an RFP for a 60-month fleet management and vehicle lease service; Andy Ngubane is the enquiry contact.",
    "latestActivity": "ATNS published and updated a 60-month fleet management RFP; tender records name Andy Ngubane as the enquiry contact.",
    "activityDate": "2026-09-16",
    "activitySource": "https://easytenders.co.za/tenders/atns-rfp12-06-2026-27-bs-fleet-management-237417-8343",
    "activityEvidence": "Fleet management RFP with addenda and pricing schedule.",
    "whyNow": "Active fleet procurement is a strong trigger for an evidence/assurance prototype.",
    "personalisation": "ATNS published an RFP for a 60-month fleet management and vehicle lease service; Andy Ngubane is the enquiry contact.",
    "trackingCode": "151pi7z1yh"
  }
];

export function getProspect(id: string) {
  return prospects.find((p) => p.id.toLowerCase() === id.toLowerCase());
}
